name: Build & Deploy Demo to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "demo/demo.html"
      - "demo/flavours.html"
      - "package.json"
      - "postcss.config.js"
      - ".github/workflows/deploy.yml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install NPM dependencies
        run: npm ci

      - name: Ensure `dist/` folder exists
        run: mkdir -p dist

      - name: Build CSS & JS
        run: npm run build

      - name: Upload theme dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: theme-dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download built theme dist
        uses: actions/download-artifact@v4
        with:
          name: theme-dist
          path: dist/

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Prepare `_site` directory
        run: |
          mkdir -p _site/dist
          # rewrite demo paths and generate index.html
          sed 's|\.\./dist/|./dist/|g' demo/demo.html > _site/index.html
          # copy flavours.html alongside
          cp demo/flavours.html _site/flavours.html
          # copy all built CSS/JS into `_site/dist/`
          cp -R dist/* _site/dist/

      - name: Upload `_site` for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
