name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "demo/demo.html" # Trigger deployment when the demo is updated
      - "dist/**" # Trigger deployment when the theme is updated

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment content
        run: |
          mkdir _site
          cp demo/demo.html _site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
