name: Build & Deploy Demo to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "demo/demo.html"
      - "demo/flavours.html"    # ← add this
      - "package.json"
      - "postcss.config.js"
      - ".github/workflows/deploy.yml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: node-version: "18"
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: theme-dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: theme-dist
          path: dist/
      - uses: actions/configure-pages@v4

      - name: Prepare _site directory
        run: |
          mkdir -p _site/dist
          # rewrite paths in demo.html → index.html
          sed 's|\.\./dist/|./dist/|g' demo/demo.html > _site/index.html
          # copy flavours.html verbatim
          cp demo/flavours.html _site/flavours.html
          # copy all CSS/JS
          cp -R dist/* _site/dist/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - uses: actions/deploy-pages@v4
